#!/bin/zsh

cmd_tkg_conf() {
  case "$1" in
    '-h' | '--help')
      stdout "Usage: ${funcstack[1]} [OPTION]"
      stdout "Options:"
      stdout "  -h, --help    Show this help message and exit"
      stdout "  -s, --link    Create a symlink to the frogminer config file"
      ;;
    '-e' | '--edit')
      local cwd="$(pwd)"
      local user_cfg="$cwd/user-settings.cfg"
      local real_cfg="$XDG_CONFIG_HOME/dotfiles/frogminer/$(basename $cwd).cfg"

      if is_link "$user_cfg"; then
        "$VISUAL" "$user_cfg"
      elif is_file "$real_cfg"; then
        "$VISUAL" "$real_cfg"
      fi
      ;;
    '-s' | '--link')
      local real_dir="$XDG_CONFIG_HOME/dotfiles/frogminer"
      local conf_dir="$XDG_CONFIG_HOME/frogminer"

      local cwd="$(pwd)"
      local real_cfg="$real_dir/$(basename $cwd).cfg"
      local user_cfg="$cwd/user-settings.cfg"

      if is_file "$real_cfg"; then
        if is_real_dir "$conf_dir"; then
          stderr "Error: '$conf_dir' already exists. Please remove it first."
          return 1
        elif ! is_link "$conf_dir"; then
          stdout "Creating symlink: $real_dir -> $conf_dir"
          ln -s "$real_dir" "$conf_dir"
        fi

        stdout "Creating symlink: $real_cfg -> $user_cfg"
        ln -sf "$real_cfg" "$user_cfg"

        return 0
      fi
      ;;
    *)
      stderr "Error: Invalid argument '$1'"
      ${funcstack[1]} --help
      return 1
      ;;
  esac
}
