#!/bin/zsh

cmd_os_release_json() {
  local code=$(cat <<'EOF'
import json

with open("/etc/os-release") as f:
  d = {}
  for line in f:
      k, v = line.rstrip().split("=")
      if v.startswith('"'):
          v = v[1:-1]
      d[k] = v
print(json.dumps(d))
EOF
)

  local os_release_json=$(python3 -c "$code")

  if [[ $? -ne 0 ]]; then
    stderr "Failed to get os-release"
    return 1
  fi

  local os_release_data=$(stdout "$os_release_json" | jq -r '.')

  if [[ $? -ne 0 ]]; then
      stderr "jq is not installed, install it to parse the json output"
      stderr "$os_release_json"
      return 1
  fi

  stdout "$os_release_data"
}
