#!/bin/zsh

cmd_pulse_eq() {
  if [[ -z "${1}" ]]; then
    stdout "Usage: ${0} [ device_name ]"
    return 0
  fi

  local conf="${ZDOTDIR}/private/pulse-eq.conf"

  if [[ -f "${conf}" ]]; then
    source "${conf}"
  else
    stderr "Could not source ${conf}"
    return 2
  fi

  local preset="${device_map[$1]}"

  if [[ -z "${preset}" ]]; then
    stderr "Cannot find preset for device name '${1}'"
    return 3
  fi

  pulseeffects --load-preset "${preset}"
  gsettings set com.github.wwmm.pulseeffects last-used-output-preset "${preset}"
}
