#!/bin/zsh

typeset -A os_info

while IFS='=' read -r key value; do
  # Remove quotes if present
  value="${value//\"/""}"
  os_info[$key]=$value
done </etc/os-release

# Access the values
echo "NAME: ${os_info[NAME]}"
echo "PRETTY_NAME: ${os_info[PRETTY_NAME]}"
echo "ID: ${os_info[ID]}"
echo "ID_LIKE: ${os_info[ID_LIKE]}"
echo "BUILD_ID: ${os_info[BUILD_ID]}"
echo "ANSI_COLOR: ${os_info[ANSI_COLOR]}"
echo "HOME_URL: ${os_info[HOME_URL]}"
echo "DOCUMENTATION_URL: ${os_info[DOCUMENTATION_URL]}"
echo "SUPPORT_URL: ${os_info[SUPPORT_URL]}"
echo "BUG_REPORT_URL: ${os_info[BUG_REPORT_URL]}"
echo "PRIVACY_POLICY_URL: ${os_info[PRIVACY_POLICY_URL]}"
echo "LOGO: ${os_info[LOGO]}"
