#!/bin/zsh

cmd_verify_archive() {
  local num_threads=1

  # --- Parse command-line options ---
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -p|--parallel)
        if [[ -n "$2" && "$2" -ge 1 ]]; then
          num_threads="$2"
          shift 2
        else
          stderr "Error: Option '$1' requires a positive integer argument for the number of threads."
          return 1
        fi
        ;;
      *)
        break # Stop processing options, assume remaining arguments are filenames
        ;;
    esac
  done

  if [[ $# -eq 0 ]]; then
    stderr "Usage: ${0##*/} [-p|--parallel <num_threads>] <filename1> [filename2 ...]"
    return 1
  fi

  # --- Run verification ---
  if [[ "$num_threads" -gt 1 ]]; then
    stdout "Verifying archives in parallel using $num_threads threads..."
    # TODO: fix execution using GNU parallal
    # SHELL=$(which zsh) parallel --jobs "${num_threads}" cmd_verify_and_report ::: "$@"
    # env_parallel --jobs "${num_threads}" --env verify_and_report verify_and_report ::: "$@"
  else
    stdout "Verifying archives sequentially..."
    for archive_file in "$@"; do
      cmd_verify_and_report "$archive_file"
    done
  fi
}
