#!/bin/zsh

cmd_zsh_functions() {
  case "${1}" in
    '-l' | 'list')
      print -l ${(ok)functions}
      ;;
    '-c' | 'check')
      typeset -f "$2" > /dev/null
      (( $? == 0 )) && stdout 'true' || stdout 'false'
      ;;
    '-h' | 'help')
      stdout "Usage: $0 [OPTIONS]"
      stdout "Running without any option will trigger check operation"
      stdout ""
      stdout "  -l, list   list all defined functions"
      stdout "  -c, check  check whether the given name is a valid function, return true or false"
      stdout "  -h, help   show help message"
      ;;
    *)
      "${funcstack[1]}" help
      ;;
  esac
}
