#!/bin/zsh
# ================================================
# File 01_alias; common shell alias initialization
# ================================================

# Command replacements
if has_command bat; then
  alias cat='bat'
fi

if has_command duf; then
  alias df='duf'
else
  alias df='df -h'
fi

if has_command gdu; then
  alias du='gdu'
else
  alias du='du -h'
  alias ds='du -hs'
fi

if has_command eza; then
  alias ls="eza ${LS_ARGS}"
  alias ll="eza ${LS_ARGS} -l"
  alias la="eza ${LS_ARGS} -a"
  alias lla="eza ${LS_ARGS} -al"
else
  alias ls="ls ${LS_ARGS}"
  alias ll="ls ${LS_ARGS} -l"
  alias la="ls ${LS_ARGS} -a"
  alias lla="ls ${LS_ARGS} -al"
fi

if has_command docker; then
  alias docker-images="docker images | grep -v repo | sed 's/ \+/:/g' | cut -d: -f1,2"
  alias docker-update="docker images | xargs -L1 docker pull"
  alias docker-prune="docker system prune -a -f"
fi

# Shell command alias
alias cls="clear && printf '\e[3J'"
alias which='command -v'
alias shdir="cd ${ZDOTDIR}"

# Make some of the file manipulation programs verbose
alias mv='mv -v'
alias cp='cp -v'

# Colorize the grep command output;
# Good for your eyes when reading long log files
alias grep='grep -i --color=auto'
alias egrep='egrep -i --color=auto'
alias fgrep='fgrep -i --color=auto'

# Allow aliases to be sudo’ed
alias sudo='sudo '

# Reloads the current shell
alias reload="exec ${SHELL} -l"
