#!/bin/zsh
# =============================================================
# File 03_macos; macos specific alias and environment variables
# =============================================================

# Bail out if not sourced from macos
if [[ "${OS_NAME}" != 'macos' ]]; then
  return 1
fi

# Initialize homebrew stuff
if [[ ! -z "${HOMEBREW_PREFIX}" ]]; then
  export LC_ALL='en_US.UTF-8'
  export HOMEBREW_GNU_UTILS="${HOMEBREW_GNU_UTILS:-true}"

  if [[ "${HOMEBREW_GNU_UTILS}" == 'true' ]]; then
    # GNU utilities and manpage
    for gnu in $(echo -e 'coreutils findutils gnu-indent gnu-which gnu-sed gnu-tar'); do
      gnu_lib="${HOMEBREW_PREFIX}/opt/${gnu}/libexec"

      if [[ -r "${gnu_lib}" ]]; then
        path_munge "${gnu_lib}/gnubin"
      fi

      unset gnu_lib
    done
  fi

  # Homebrew local/sbin
  path_munge "${HOMEBREW_PREFIX}/sbin"

  # Ruby
  path_munge "${HOMEBREW_PREFIX}/opt/ruby/bin"

  # Python
  path_munge "${HOMEBREW_PREFIX}/opt/python/libexec/bin"

  # Cask options
  zsh-in "${ZDOTDIR}/private/homebrew.zsh"
  export HOMEBREW_CASK_OPTS='--appdir=/Applications'
fi

# ls enhancement
if (( ${+commands[gls]} )); then
  # if gnu coreutils is installed
  alias ls="gls ${LS_ARGS}"
  alias ll="gls ${LS_ARGS} -l"
  alias la="gls ${LS_ARGS} -a"
else
  alias ll="ls -l"
  alias la="ls -a"
fi
