AllCops:
  TargetRubyVersion: 3.4
  NewCops: disable

# --- Code Style ---
# For scripts, extensive class/module docs is overkill.
Style/Documentation:
  Enabled: false

# Encourages adding # frozen_string_literal: true
Style/FrozenStringLiteralComment:
  Enabled: true

# Enforce double quote for consistency and _developer_happiness_.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Encourages using &:method over { |x| x.method }
Style/SymbolProc:
  Enabled: true

# --- Layout / Formatting ---
Layout/EmptyLinesAroundBlockBody:
  Enabled: true

# Check that the keys, separators, and values of a multi-line hash literal are aligned
Layout/HashAlignment:
  EnforcedHashRocketStyle: table

# Standard Ruby indentation
Layout/IndentationWidth:
  Width: 2

# Default is 80, often too short for modern screens.
Layout/LineLength:
  Max: 120

# For Rake tasks or scripts with DSLs, blocks can get long.
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 500

# Allow slightly more complex lines for for our script.
Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 50
