# frozen_string_literal: true

source "https://rubygems.org"

gem "logging"
gem "slop"

group :development, :test do
  gem "debug", require: false
  gem "rubocop", require: false
  gem "solargraph", require: false
end
