#!/bin/zsh

gcp() {
  if ! check_command gcloud; then
    return 1
  fi

  typeset -A args

  args[i]='install'
  args[up]='update'
  args[ls]='list'
  args[rm]='remove'
  args[rs]='restore'
  args[re]='reinstall'
  args[repo]='repositories'
  args[help]='--help'

  # Iterate key-val for debugging
  # for key val in ${(kv)args}; do
  #   echo "$key -> $val"
  # done

  local arg="${args[$1]}"
  local cmd='gcloud components'

  if [[ -z "${arg}" ]]; then
    "${cmd}" "${@}"
  else
    "${cmd}" "${arg}" "${@:2}"
  fi
}
