#!/bin/zsh

fn_is_file() {
  local quiet=0
  while [[ "$1" == -* ]]; do
    case "$1" in
      '-q' | '--quiet')
        quiet=1
        shift
        ;;
      -*)
        stderr "Unknown option: $1"
        return 1
        ;;
    esac
  done

  local file="$1"

  if [[ -f "$file" ]] && [[ -r "$file" ]]; then
    (( ! quiet )) && stdout "File: $(realpath $1)"
    return 0
  fi

  (( ! quiet )) && stderr "Error: File '$(realpath $1)' is not accessible."
  return 1
}
