#!/bin/zsh
# File: ls_type
# Detects the type of `ls` command available on the system.

ls_type() {
  if $(ls --color -d "$HOME" >/dev/null 2>&1); then
    stdout "gnu"
  elif $(ls -G -d "$HOME" >/dev/null 2>&1); then
    stdout "bsd"
  else
    stdout "solaris"
  fi
}
