#!/bin/zsh
# File : path_munge; Validate and add a directory to the PATH variable.
# Usage: path_munge [directory] [before|after]

path_munge() {
  if [[ -d "$1" ]] && [[ -r "$1" ]] &&
    ! echo "$PATH" | grep -Eq "(^|:)$1($|:)"; then
    if [[ "$2" = "after" ]]; then
      PATH="$PATH:$1"
    else
      PATH="$1:$PATH"
    fi
  fi
}
